/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Christian Sacancela
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JPanelNS = new javax.swing.JPanel();
        JLabelNS = new javax.swing.JLabel();
        JPanelNP = new javax.swing.JPanel();
        JLabelNP = new javax.swing.JLabel();
        JPanelP = new javax.swing.JPanel();
        JLabelP = new javax.swing.JLabel();
        JPanelC = new javax.swing.JPanel();
        JLabelC = new javax.swing.JLabel();
        JPanelPr = new javax.swing.JPanel();
        JLabelPr = new javax.swing.JLabel();
        JPanelM = new javax.swing.JPanel();
        JLabelM = new javax.swing.JLabel();
        JPanelCat = new javax.swing.JPanel();
        JLabelCat = new javax.swing.JLabel();
        JPanelConf = new javax.swing.JPanel();
        JLabelConf = new javax.swing.JLabel();
        JPanelU = new javax.swing.JPanel();
        JLabelU = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtSP = new javax.swing.JTextField();
        btnU = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCodeP = new javax.swing.JTextField();
        txtDesP = new javax.swing.JTextField();
        txtPricePP = new javax.swing.JTextField();
        txtPriceSP = new javax.swing.JTextField();
        cbxProviderP = new javax.swing.JComboBox<>();
        cbxMeasureP = new javax.swing.JComboBox<>();
        cbxCatP = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnNewP = new javax.swing.JButton();
        btnRegisterP = new javax.swing.JButton();
        btnModifyP = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableP = new javax.swing.JTable();
        PagerP = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNameC = new javax.swing.JTextField();
        txtPhoneC = new javax.swing.JTextField();
        btnNewC = new javax.swing.JButton();
        btnRegisterC = new javax.swing.JButton();
        btnModifyC = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtAddressC = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableC = new javax.swing.JTable();
        PagerC = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNamePr = new javax.swing.JTextField();
        txtPhonePr = new javax.swing.JTextField();
        btnNewPr = new javax.swing.JButton();
        btnRegisterPr = new javax.swing.JButton();
        btnModifyPr = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtAddressPr = new javax.swing.JTextPane();
        jLabel15 = new javax.swing.JLabel();
        txtRucPr = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablePr = new javax.swing.JTable();
        PagerPr = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtNameU = new javax.swing.JTextField();
        btnNewU = new javax.swing.JButton();
        btnRegisterU = new javax.swing.JButton();
        btnModifyU = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtUserU = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cbxRoleU = new javax.swing.JComboBox<>();
        cbxCashU = new javax.swing.JComboBox<>();
        txtPassU = new javax.swing.JPasswordField();
        jScrollPane8 = new javax.swing.JScrollPane();
        TableU = new javax.swing.JTable();
        PagerU = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtNameCat = new javax.swing.JTextField();
        btnNewCat = new javax.swing.JButton();
        btnRegisterCat = new javax.swing.JButton();
        btnModifyCat = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        TableCat = new javax.swing.JTable();
        PagerCat = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txtNameM = new javax.swing.JTextField();
        btnNewM = new javax.swing.JButton();
        btnRegisterM = new javax.swing.JButton();
        btnModifyM = new javax.swing.JButton();
        txtAbbM = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        TableM = new javax.swing.JTable();
        PagerM = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableNS = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        txtCodeNS = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtProductNS = new javax.swing.JTextField();
        txtAmountNS = new javax.swing.JTextField();
        txtPriceNS = new javax.swing.JTextField();
        txtTotalNS = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtStockNS = new javax.swing.JTextField();
        btnGenerateNS = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        JLabelTotalPay = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        TableS = new javax.swing.JTable();
        PagerS = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        TablePurchase = new javax.swing.JTable();
        PagerPurchase = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        txtRUCCompany = new javax.swing.JTextField();
        txtPhoneCompany = new javax.swing.JTextField();
        btnModifyCompany = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        txtAddressCompany = new javax.swing.JTextPane();
        txtNameCompany = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextPane();
        jLabel47 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        TableNP = new javax.swing.JTable();
        jLabel34 = new javax.swing.JLabel();
        txtCodeNP = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txtProductNP = new javax.swing.JTextField();
        txtAmountNP = new javax.swing.JTextField();
        txtPriceNP = new javax.swing.JTextField();
        txtTotalNP = new javax.swing.JTextField();
        btnGenerateNP = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        JLabelTotalPay1 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLabelNS.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JLabelNS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelNS.setText("Nueva Venta");

        javax.swing.GroupLayout JPanelNSLayout = new javax.swing.GroupLayout(JPanelNS);
        JPanelNS.setLayout(JPanelNSLayout);
        JPanelNSLayout.setHorizontalGroup(
            JPanelNSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLabelNS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        JPanelNSLayout.setVerticalGroup(
            JPanelNSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelNSLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLabelNS)
                .addContainerGap())
        );

        jPanel1.add(JPanelNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 40));

        JLabelNP.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JLabelNP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelNP.setText("Nueva Compra");

        javax.swing.GroupLayout JPanelNPLayout = new javax.swing.GroupLayout(JPanelNP);
        JPanelNP.setLayout(JPanelNPLayout);
        JPanelNPLayout.setHorizontalGroup(
            JPanelNPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLabelNP, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        JPanelNPLayout.setVerticalGroup(
            JPanelNPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelNPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelNP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelNP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 200, 40));

        JLabelP.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JLabelP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelP.setText("Productos");

        javax.swing.GroupLayout JPanelPLayout = new javax.swing.GroupLayout(JPanelP);
        JPanelP.setLayout(JPanelPLayout);
        JPanelPLayout.setHorizontalGroup(
            JPanelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLabelP, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        JPanelPLayout.setVerticalGroup(
            JPanelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 200, 40));

        JLabelC.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JLabelC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelC.setText("Clientes");

        javax.swing.GroupLayout JPanelCLayout = new javax.swing.GroupLayout(JPanelC);
        JPanelC.setLayout(JPanelCLayout);
        JPanelCLayout.setHorizontalGroup(
            JPanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLabelC, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        JPanelCLayout.setVerticalGroup(
            JPanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 200, 40));

        JLabelPr.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JLabelPr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelPr.setText("Proveedores");

        javax.swing.GroupLayout JPanelPrLayout = new javax.swing.GroupLayout(JPanelPr);
        JPanelPr.setLayout(JPanelPrLayout);
        JPanelPrLayout.setHorizontalGroup(
            JPanelPrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLabelPr, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        JPanelPrLayout.setVerticalGroup(
            JPanelPrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelPrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelPr)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelPr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 200, 40));

        JLabelM.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JLabelM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelM.setText("Medidas");

        javax.swing.GroupLayout JPanelMLayout = new javax.swing.GroupLayout(JPanelM);
        JPanelM.setLayout(JPanelMLayout);
        JPanelMLayout.setHorizontalGroup(
            JPanelMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLabelM, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        JPanelMLayout.setVerticalGroup(
            JPanelMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelM)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 200, 40));

        JLabelCat.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JLabelCat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelCat.setText("Categorías");

        javax.swing.GroupLayout JPanelCatLayout = new javax.swing.GroupLayout(JPanelCat);
        JPanelCat.setLayout(JPanelCatLayout);
        JPanelCatLayout.setHorizontalGroup(
            JPanelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLabelCat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        JPanelCatLayout.setVerticalGroup(
            JPanelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelCatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLabelCat)
                .addContainerGap())
        );

        jPanel1.add(JPanelCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 200, 40));

        JLabelConf.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JLabelConf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelConf.setText("Configuración");

        javax.swing.GroupLayout JPanelConfLayout = new javax.swing.GroupLayout(JPanelConf);
        JPanelConf.setLayout(JPanelConfLayout);
        JPanelConfLayout.setHorizontalGroup(
            JPanelConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLabelConf, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        JPanelConfLayout.setVerticalGroup(
            JPanelConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelConfLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLabelConf)
                .addContainerGap())
        );

        jPanel1.add(JPanelConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 200, 40));

        JLabelU.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JLabelU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelU.setText("Usuarios");

        javax.swing.GroupLayout JPanelULayout = new javax.swing.GroupLayout(JPanelU);
        JPanelU.setLayout(JPanelULayout);
        JPanelULayout.setHorizontalGroup(
            JPanelULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLabelU, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        JPanelULayout.setVerticalGroup(
            JPanelULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelULayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelU)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 200, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 620));

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema de Ventas");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 45, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 130));

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(txtSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 170, 30));

        btnU.setText("Usuarios");
        jPanel3.add(btnU, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, -1, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1050, 130));

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Producto"));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Código");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Decripción");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Precio Compra");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Precio Venta");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Proveedor");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Medida");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Categoría");

        btnNewP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNewP.setText("Nuevo");

        btnRegisterP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRegisterP.setText("Registrar");

        btnModifyP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnModifyP.setText("Modificar");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(btnNewP)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegisterP)
                        .addGap(18, 18, 18)
                        .addComponent(btnModifyP))
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCodeP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8))
                                    .addGap(49, 49, 49))
                                .addGroup(jPanel13Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPricePP)
                                .addComponent(txtPriceSP)
                                .addComponent(cbxProviderP, 0, 150, Short.MAX_VALUE)
                                .addComponent(cbxMeasureP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxCatP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                            .addComponent(txtDesP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodeP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDesP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPricePP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPriceSP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxProviderP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbxMeasureP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCatP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(95, 95, 95)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegisterP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifyP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 340, 490));

        TableP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Precio", "Cantidad", "Medida", "Estado"
            }
        ));
        jScrollPane1.setViewportView(TableP);
        if (TableP.getColumnModel().getColumnCount() > 0) {
            TableP.getColumnModel().getColumn(4).setHeaderValue("");
        }

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 670, -1));

        javax.swing.GroupLayout PagerPLayout = new javax.swing.GroupLayout(PagerP);
        PagerP.setLayout(PagerPLayout);
        PagerPLayout.setHorizontalGroup(
            PagerPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        PagerPLayout.setVerticalGroup(
            PagerPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel4.add(PagerP, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 670, -1));

        jTabbedPane1.addTab("tab1", jPanel4);

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Cliente"));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Nombre");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Teléfono");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Dirección");

        btnNewC.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNewC.setText("Nuevo");

        btnRegisterC.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRegisterC.setText("Registrar");

        btnModifyC.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnModifyC.setText("Modificar");

        jScrollPane6.setViewportView(txtAddressC);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(btnNewC)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegisterC)
                        .addGap(18, 18, 18)
                        .addComponent(btnModifyC)
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNameC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPhoneC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46))))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNameC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPhoneC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegisterC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifyC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 340, 340));

        TableC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Telefono", "Direccion", "Estado"
            }
        ));
        jScrollPane2.setViewportView(TableC);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 670, -1));

        javax.swing.GroupLayout PagerCLayout = new javax.swing.GroupLayout(PagerC);
        PagerC.setLayout(PagerCLayout);
        PagerCLayout.setHorizontalGroup(
            PagerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        PagerCLayout.setVerticalGroup(
            PagerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel5.add(PagerC, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 670, -1));

        jTabbedPane1.addTab("tab2", jPanel5);

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Proveedor"));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Nombre");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Teléfono");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Dirección");

        btnNewPr.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNewPr.setText("Nuevo");

        btnRegisterPr.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRegisterPr.setText("Registrar");

        btnModifyPr.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnModifyPr.setText("Modificar");

        jScrollPane5.setViewportView(txtAddressPr);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Ruc");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(btnNewPr)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegisterPr)
                        .addGap(18, 18, 18)
                        .addComponent(btnModifyPr))
                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel16Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRucPr, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel16Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                            .addComponent(txtNamePr, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel16Layout.createSequentialGroup()
                            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPhonePr, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(jScrollPane5)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtRucPr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNamePr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtPhonePr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel14))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewPr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegisterPr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifyPr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 340, 410));

        TablePr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "RUC", "Nombre", "Telefono", "Direccion", "Estado"
            }
        ));
        jScrollPane4.setViewportView(TablePr);

        jPanel6.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 670, -1));

        javax.swing.GroupLayout PagerPrLayout = new javax.swing.GroupLayout(PagerPr);
        PagerPr.setLayout(PagerPrLayout);
        PagerPrLayout.setHorizontalGroup(
            PagerPrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        PagerPrLayout.setVerticalGroup(
            PagerPrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel6.add(PagerPr, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 670, -1));

        jTabbedPane1.addTab("tab3", jPanel6);

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Usuario"));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Nombre");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Contraseña");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("Caja");

        btnNewU.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNewU.setText("Nuevo");

        btnRegisterU.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRegisterU.setText("Registrar");

        btnModifyU.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnModifyU.setText("Modificar");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setText("Usuario");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setText("Rol");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel17Layout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUserU, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel17Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                            .addComponent(txtNameU, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel17Layout.createSequentialGroup()
                            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbxRoleU, 0, 150, Short.MAX_VALUE)
                                .addComponent(cbxCashU, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPassU))))
                    .addComponent(jLabel20))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(btnNewU)
                .addGap(18, 18, 18)
                .addComponent(btnRegisterU)
                .addGap(18, 18, 18)
                .addComponent(btnModifyU)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtUserU, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNameU, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(txtPassU, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cbxCashU, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cbxRoleU, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewU, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegisterU, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifyU, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 340, 420));

        TableU.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Usuario", "Nombre", "Rol", "Caja", "Estado"
            }
        ));
        jScrollPane8.setViewportView(TableU);
        if (TableU.getColumnModel().getColumnCount() > 0) {
            TableU.getColumnModel().getColumn(1).setHeaderValue("Usuario");
            TableU.getColumnModel().getColumn(3).setHeaderValue("Rol");
            TableU.getColumnModel().getColumn(4).setHeaderValue("Caja");
        }

        jPanel7.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 670, -1));

        javax.swing.GroupLayout PagerULayout = new javax.swing.GroupLayout(PagerU);
        PagerU.setLayout(PagerULayout);
        PagerULayout.setHorizontalGroup(
            PagerULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        PagerULayout.setVerticalGroup(
            PagerULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel7.add(PagerU, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 670, -1));

        jTabbedPane1.addTab("tab4", jPanel7);

        jPanel8.setBackground(new java.awt.Color(204, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Nueva Categoría"));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("Nombre");

        btnNewCat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNewCat.setText("Nueva");

        btnRegisterCat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRegisterCat.setText("Registrar");

        btnModifyCat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnModifyCat.setText("Modificar");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(btnNewCat)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegisterCat)
                        .addGap(18, 18, 18)
                        .addComponent(btnModifyCat))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(80, 80, 80)
                        .addComponent(txtNameCat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNameCat, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(56, 56, 56)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewCat, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegisterCat, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifyCat, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 340, 240));

        TableCat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Estado"
            }
        ));
        jScrollPane9.setViewportView(TableCat);

        jPanel8.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 670, -1));

        javax.swing.GroupLayout PagerCatLayout = new javax.swing.GroupLayout(PagerCat);
        PagerCat.setLayout(PagerCatLayout);
        PagerCatLayout.setHorizontalGroup(
            PagerCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        PagerCatLayout.setVerticalGroup(
            PagerCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel8.add(PagerCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 670, -1));

        jTabbedPane1.addTab("tab5", jPanel8);

        jPanel9.setBackground(new java.awt.Color(204, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder("Nueva Medida"));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setText("Nombre");

        btnNewM.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNewM.setText("Nueva");

        btnRegisterM.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRegisterM.setText("Registrar");

        btnModifyM.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnModifyM.setText("Modificar");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel24.setText("Abreviatura");
        jLabel24.setToolTipText("");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(btnNewM)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegisterM)
                        .addGap(18, 18, 18)
                        .addComponent(btnModifyM))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(91, 91, 91)))
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNameM, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAbbM, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtNameM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAbbM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegisterM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifyM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel9.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 340, 290));

        TableM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Abreviatura", "Estado"
            }
        ));
        jScrollPane10.setViewportView(TableM);

        jPanel9.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 670, -1));

        javax.swing.GroupLayout PagerMLayout = new javax.swing.GroupLayout(PagerM);
        PagerM.setLayout(PagerMLayout);
        PagerMLayout.setHorizontalGroup(
            PagerMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        PagerMLayout.setVerticalGroup(
            PagerMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel9.add(PagerM, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 670, -1));

        jTabbedPane1.addTab("tab6", jPanel9);

        jPanel10.setBackground(new java.awt.Color(153, 255, 153));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableNS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descripción", "Cantidad", "Precio", "Total"
            }
        ));
        jScrollPane3.setViewportView(TableNS);

        jPanel10.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1030, 410));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setText("Código");
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        jPanel10.add(txtCodeNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 100, 26));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel25.setText("Producto");
        jPanel10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel26.setText("Cantidad");
        jPanel10.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel27.setText("Precio");
        jPanel10.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel28.setText("Total");
        jPanel10.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, -1, -1));
        jPanel10.add(txtProductNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 160, 26));
        jPanel10.add(txtAmountNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 60, 26));
        jPanel10.add(txtPriceNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 70, 26));
        jPanel10.add(txtTotalNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 70, 26));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel29.setText("Stock");
        jPanel10.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, -1));
        jPanel10.add(txtStockNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 60, 26));

        btnGenerateNS.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnGenerateNS.setText("Generar");
        jPanel10.add(btnGenerateNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, -1, -1));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel30.setText("Cliente");
        jPanel10.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        jPanel10.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 150, 26));
        jPanel10.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 110, 26));
        jPanel10.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 550, 140, 26));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel31.setText("Total a pagar");
        jPanel10.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 550, -1, -1));

        JLabelTotalPay.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JLabelTotalPay.setText("...");
        jPanel10.add(JLabelTotalPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 550, -1, -1));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel32.setText("Paga con");
        jPanel10.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, -1, -1));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel33.setText("Vuelto");
        jPanel10.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, -1, -1));

        jTabbedPane1.addTab("tab7", jPanel10);

        jPanel11.setBackground(new java.awt.Color(153, 255, 153));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Total", "Fecha"
            }
        ));
        jScrollPane11.setViewportView(TableS);

        jPanel11.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1030, 410));

        javax.swing.GroupLayout PagerSLayout = new javax.swing.GroupLayout(PagerS);
        PagerS.setLayout(PagerSLayout);
        PagerSLayout.setHorizontalGroup(
            PagerSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        PagerSLayout.setVerticalGroup(
            PagerSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel11.add(PagerS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 1030, 70));

        jTabbedPane1.addTab("tab8", jPanel11);

        jPanel12.setBackground(new java.awt.Color(153, 255, 153));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablePurchase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Proveedor", "Total", "Fecha"
            }
        ));
        jScrollPane12.setViewportView(TablePurchase);

        jPanel12.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1030, 410));

        javax.swing.GroupLayout PagerPurchaseLayout = new javax.swing.GroupLayout(PagerPurchase);
        PagerPurchase.setLayout(PagerPurchaseLayout);
        PagerPurchaseLayout.setHorizontalGroup(
            PagerPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        PagerPurchaseLayout.setVerticalGroup(
            PagerPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel12.add(PagerPurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 1030, 70));

        jTabbedPane1.addTab("tab9", jPanel12);

        jPanel14.setBackground(new java.awt.Color(153, 255, 153));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la Empresa"));

        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel39.setText("Nombre");

        jLabel44.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel44.setText("Teléfono");

        jLabel45.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel45.setText("Dirección");

        btnModifyCompany.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnModifyCompany.setText("Modificar");

        jScrollPane13.setViewportView(txtAddressCompany);

        jLabel46.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel46.setText("RUC");

        jScrollPane14.setViewportView(txtMessage);

        jLabel47.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel47.setText("Mensaje");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addComponent(jLabel44)
                            .addComponent(jLabel45)
                            .addComponent(jLabel46))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhoneCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRUCCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNameCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModifyCompany)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRUCCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46))
                .addGap(26, 26, 26)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(txtNameCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(txtPhoneCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel45)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel47)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btnModifyCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jPanel14.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 340, 470));

        jTabbedPane1.addTab("tab10", jPanel14);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1045, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab11", jPanel20);

        jPanel21.setBackground(new java.awt.Color(153, 255, 153));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableNP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descripción", "Cantidad", "Precio", "Total"
            }
        ));
        jScrollPane7.setViewportView(TableNP);

        jPanel21.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1030, 410));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel34.setText("Código");
        jPanel21.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        jPanel21.add(txtCodeNP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 100, 26));

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel35.setText("Producto");
        jPanel21.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel36.setText("Cantidad");
        jPanel21.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel37.setText("Precio");
        jPanel21.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel38.setText("Total");
        jPanel21.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, -1, -1));
        jPanel21.add(txtProductNP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 160, 26));
        jPanel21.add(txtAmountNP, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 60, 26));
        jPanel21.add(txtPriceNP, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 70, 26));
        jPanel21.add(txtTotalNP, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 70, 26));

        btnGenerateNP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnGenerateNP.setText("Generar");
        jPanel21.add(btnGenerateNP, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, -1, -1));

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel40.setText("Proveedor");
        jPanel21.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        jPanel21.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 150, 26));
        jPanel21.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 110, 26));
        jPanel21.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 550, 140, 26));

        jLabel41.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel41.setText("Total a pagar");
        jPanel21.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 550, -1, -1));

        JLabelTotalPay1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JLabelTotalPay1.setText("...");
        jPanel21.add(JLabelTotalPay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 550, -1, -1));

        jLabel42.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel42.setText("Paga con");
        jPanel21.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, -1, -1));

        jLabel43.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel43.setText("Vuelto");
        jPanel21.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, -1, -1));

        jTabbedPane1.addTab("Nueva Compra", jPanel21);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 1050, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelC;
    private javax.swing.JLabel JLabelCat;
    private javax.swing.JLabel JLabelConf;
    private javax.swing.JLabel JLabelM;
    private javax.swing.JLabel JLabelNP;
    private javax.swing.JLabel JLabelNS;
    private javax.swing.JLabel JLabelP;
    private javax.swing.JLabel JLabelPr;
    private javax.swing.JLabel JLabelTotalPay;
    private javax.swing.JLabel JLabelTotalPay1;
    private javax.swing.JLabel JLabelU;
    private javax.swing.JPanel JPanelC;
    private javax.swing.JPanel JPanelCat;
    private javax.swing.JPanel JPanelConf;
    private javax.swing.JPanel JPanelM;
    private javax.swing.JPanel JPanelNP;
    private javax.swing.JPanel JPanelNS;
    private javax.swing.JPanel JPanelP;
    private javax.swing.JPanel JPanelPr;
    private javax.swing.JPanel JPanelU;
    private javax.swing.JPanel PagerC;
    private javax.swing.JPanel PagerCat;
    private javax.swing.JPanel PagerM;
    private javax.swing.JPanel PagerP;
    private javax.swing.JPanel PagerPr;
    private javax.swing.JPanel PagerPurchase;
    private javax.swing.JPanel PagerS;
    private javax.swing.JPanel PagerU;
    private javax.swing.JTable TableC;
    private javax.swing.JTable TableCat;
    private javax.swing.JTable TableM;
    private javax.swing.JTable TableNP;
    private javax.swing.JTable TableNS;
    private javax.swing.JTable TableP;
    private javax.swing.JTable TablePr;
    private javax.swing.JTable TablePurchase;
    private javax.swing.JTable TableS;
    private javax.swing.JTable TableU;
    private javax.swing.JButton btnGenerateNP;
    private javax.swing.JButton btnGenerateNS;
    private javax.swing.JButton btnModifyC;
    private javax.swing.JButton btnModifyCat;
    private javax.swing.JButton btnModifyCompany;
    private javax.swing.JButton btnModifyM;
    private javax.swing.JButton btnModifyP;
    private javax.swing.JButton btnModifyPr;
    private javax.swing.JButton btnModifyU;
    private javax.swing.JButton btnNewC;
    private javax.swing.JButton btnNewCat;
    private javax.swing.JButton btnNewM;
    private javax.swing.JButton btnNewP;
    private javax.swing.JButton btnNewPr;
    private javax.swing.JButton btnNewU;
    private javax.swing.JButton btnRegisterC;
    private javax.swing.JButton btnRegisterCat;
    private javax.swing.JButton btnRegisterM;
    private javax.swing.JButton btnRegisterP;
    private javax.swing.JButton btnRegisterPr;
    private javax.swing.JButton btnRegisterU;
    private javax.swing.JButton btnU;
    private javax.swing.JComboBox<String> cbxCashU;
    private javax.swing.JComboBox<String> cbxCatP;
    private javax.swing.JComboBox<String> cbxMeasureP;
    private javax.swing.JComboBox<String> cbxProviderP;
    private javax.swing.JComboBox<String> cbxRoleU;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField txtAbbM;
    private javax.swing.JTextPane txtAddressC;
    private javax.swing.JTextPane txtAddressCompany;
    private javax.swing.JTextPane txtAddressPr;
    private javax.swing.JTextField txtAmountNP;
    private javax.swing.JTextField txtAmountNS;
    private javax.swing.JTextField txtCodeNP;
    private javax.swing.JTextField txtCodeNS;
    private javax.swing.JTextField txtCodeP;
    private javax.swing.JTextField txtDesP;
    private javax.swing.JTextPane txtMessage;
    private javax.swing.JTextField txtNameC;
    private javax.swing.JTextField txtNameCat;
    private javax.swing.JTextField txtNameCompany;
    private javax.swing.JTextField txtNameM;
    private javax.swing.JTextField txtNamePr;
    private javax.swing.JTextField txtNameU;
    private javax.swing.JPasswordField txtPassU;
    private javax.swing.JTextField txtPhoneC;
    private javax.swing.JTextField txtPhoneCompany;
    private javax.swing.JTextField txtPhonePr;
    private javax.swing.JTextField txtPriceNP;
    private javax.swing.JTextField txtPriceNS;
    private javax.swing.JTextField txtPricePP;
    private javax.swing.JTextField txtPriceSP;
    private javax.swing.JTextField txtProductNP;
    private javax.swing.JTextField txtProductNS;
    private javax.swing.JTextField txtRUCCompany;
    private javax.swing.JTextField txtRucPr;
    private javax.swing.JTextField txtSP;
    private javax.swing.JTextField txtStockNS;
    private javax.swing.JTextField txtTotalNP;
    private javax.swing.JTextField txtTotalNS;
    private javax.swing.JTextField txtUserU;
    // End of variables declaration//GEN-END:variables
}
